### ISSUE TITLE
Error with send_transaction RPC request to wallet daemon

### ISSUE THREAD

**Issue by greenpc01** [ArqTras/intuPool#2]
![image](https://user-images.githubusercontent.com/36276723/41411227-06fed5cc-7017-11e8-9830-516d6344e5bb.png)

I do not know why I got this error
Help plz

**Comment by ArqTras** [comment]
You must start simplewallet in rpc mode on port declared in pool configuration. For example simplewallet —rpc-bind-ip 127.0.0.1 —rpc-bind-port 8082 —wallet-file poolwallet — password poolwalletpassword

**Comment by greenpc01** [comment]
Very good.
thank you.
